#pragma once

#include "../Network/AddEntityPacket.h"
#include "../Network/AddGlobalEntityPacket.h"
#include "../Network/AddMobPacket.h"
#include "../Network/AddPaintingPacket.h"
#include "../Network/AddPlayerPacket.h"
#include "../Network/AnimatePacket.h"
#include "../Network/AwardStatPacket.h"
#include "../Network/BlockRegionUpdatePacket.h"
#include "../Network/ChatPacket.h"
#include "../Network/ChunkTilesUpdatePacket.h"
#include "../Network/ChunkVisibilityPacket.h"
#include "../Network/ComplexItemDataPacket.h"
#include "../Network/ContainerAckPacket.h"
#include "../Network/ContainerClickPacket.h"
#include "../Network/ContainerClosePacket.h"
#include "../Network/ContainerOpenPacket.h"
#include "../Network/ContainerSetContentPacket.h"
#include "../Network/ContainerSetDataPacket.h"
#include "../Network/ContainerSetSlotPacket.h"
#include "../Network/DisconnectPacket.h"
#include "../Network/EntityActionAtPositionPacket.h"
#include "../Network/EntityEventPacket.h"
#include "../Network/ExplodePacket.h"
#include "../Network/GameEventPacket.h"
#include "../Network/InteractPacket.h"
#include "../Network/KeepAlivePacket.h"
#include "../Network/LevelEventPacket.h"
#include "../Network/LoginPacket.h"
#include "../Network/MoveEntityPacket.h"
#include "../Network/MoveEntityPacketSmall.h"
#include "../Network/MovePlayerPacket.h"
#include "../Network/Packet.h"
#include "../Network/PacketListener.h"
#include "../Network/PlayerActionPacket.h"
#include "../Network/PlayerCommandPacket.h"
#include "../Network/PlayerInputPacket.h"
#include "../Network/PreLoginPacket.h"
#include "../Network/RemoveEntitiesPacket.h"
#include "../Network/RespawnPacket.h"

#include "../Network/SetCarriedItemPacket.h"
#include "../Network/SetEntityDataPacket.h"
#include "../Network/SetEntityMotionPacket.h"
#include "../Network/SetEquippedItemPacket.h"
#include "../Network/SetHealthPacket.h"
#include "../Network/SetRidingPacket.h"
#include "../Network/SetSpawnPositionPacket.h"
#include "../Network/SetTimePacket.h"
#include "../Network/SignUpdatePacket.h"
#include "../Network/TakeItemEntityPacket.h"
#include "../Network/TeleportEntityPacket.h"
#include "../Network/TileEventPacket.h"
#include "../Network/TileUpdatePacket.h"
#include "../Network/UseItemPacket.h"

// 1.8.2 Added
#include "../Network/AddExperienceOrbPacket.h"
#include "../Network/GetInfoPacket.h"
#include "../Network/PlayerInfoPacket.h"
#include "../Network/RemoveMobEffectPacket.h"
#include "../Network/SetCreativeModeSlotPacket.h"
#include "../Network/SetExperiencePacket.h"
#include "../Network/UpdateMobEffectPacket.h"

// 1.0.1 Added
#include "../Network/ContainerButtonClickPacket.h"
#include "../Network/TileEntityDataPacket.h"

// 1.1 Added (TU9)
#include "../Network/CustomPayloadPacket.h"

// 1.2.3
#include "../Network/RotateHeadPacket.h"

// 1.3.2
#include "../Network/ChatAutoCompletePacket.h"
#include "../Network/ClientCommandPacket.h"
#include "../Network/ClientInformationPacket.h"
#include "../Network/ClientProtocolPacket.h"
#include "../Network/LevelSoundPacket.h"
#include "../Network/PlayerAbilitiesPacket.h"
#include "../Network/ServerAuthDataPacket.h"
#include "../Network/TileDestructionPacket.h"

// 4J Added
#include "../Network/CraftItemPacket.h"
#include "../Network/TradeItemPacket.h"
#include "../Network/DebugOptionsPacket.h"
#include "../Network/ServerSettingsChangedPacket.h"
#include "../Network/TexturePacket.h"
#include "../Network/TextureAndGeometryPacket.h"
#include "../Network/ChunkVisibilityAreaPacket.h"
#include "../Network/UpdateProgressPacket.h"
#include "../Network/TextureChangePacket.h"
#include "../Network/TextureAndGeometryChangePacket.h"
#include "../Network/UpdateGameRuleProgressPacket.h"
#include "../Network/KickPlayerPacket.h"
#include "../Network/XZPacket.h"
#include "../Network/GameCommandPacket.h"

