#pragma once

#include "../WorldGen/BasicTree.h"
#include "../WorldGen/BirchFeature.h"
#include "../WorldGen/CactusFeature.h"
#include "../WorldGen/CaveFeature.h"
#include "../WorldGen/ClayFeature.h"
#include "../WorldGen/DeadBushFeature.h"
#include "../WorldGen/Feature.h"
#include "../WorldGen/FlowerFeature.h"
#include "../WorldGen/HellFireFeature.h"
#include "../WorldGen/HellPortalFeature.h"
#include "../WorldGen/HellSpringFeature.h"
#include "../WorldGen/HouseFeature.h"
#include "../WorldGen/LakeFeature.h"
#include "../WorldGen/LightGemFeature.h"
#include "../WorldGen/MonsterRoomFeature.h"
#include "../WorldGen/OreFeature.h"
#include "../WorldGen/PineFeature.h"
#include "../WorldGen/PumpkinFeature.h"
#include "../WorldGen/ReedsFeature.h"
#include "../WorldGen/SpringFeature.h"
#include "../WorldGen/SpruceFeature.h"
#include "../WorldGen/TallGrassFeature.h"
#include "../WorldGen/TreeFeature.h"

#include "../WorldGen/HugeMushroomFeature.h"
#include "../WorldGen/SandFeature.h"
#include "../WorldGen/SwampTreeFeature.h"
#include "../WorldGen/BonusChestFeature.h"
#include "../WorldGen/SpikeFeature.h"
#include "../WorldGen/EndPodiumFeature.h"

#include "../WorldGen/DesertWellFeature.h"
#include "../WorldGen/MegaTreeFeature.h"
#include "../WorldGen/VinesFeature.h"
#include "../WorldGen/GroundBushFeature.h"