#include "BgfxRenderer.h"
#include "SDLWindow.h"

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>
#include <bx/math.h>

#include "shaders/shader_minecraft.h"
// macOS Metal variants (generated by macos/build_shaders_metal.sh)
#if defined(__APPLE__) && __has_include("shaders/macos/shader_minecraft_vs_mtl.h")
#  include "shaders/macos/shader_minecraft_vs_mtl.h"
#  include "shaders/macos/shader_minecraft_fs_mtl.h"
#  define MINECRAFT_HAS_METAL_SHADERS 1
#endif

#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#define STBI_ONLY_JPEG
#define STBI_NO_STDIO
#include "../../ExternalDependency/bimg/3rdparty/stb/stb_image.h"

#include <cstdio> // for fopen/fread in LoadTextureData

BgfxRenderer g_BgfxRenderer;

// layout: float3 pos, float2 uv, uint32 color, uint32 normal, uint32 tex2 = 32 bytes
static bgfx::VertexLayout s_standardLayout;
static bool s_layoutInitialized = false;

static void InitVertexLayouts()
{
	if (s_layoutInitialized) return;
	s_standardLayout
		.begin()
		.add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
		.add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
		.add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
		.add(bgfx::Attrib::Normal, 4, bgfx::AttribType::Uint8, true)
		.add(bgfx::Attrib::TexCoord1, 4, bgfx::AttribType::Uint8, true)
		.end();
	s_layoutInitialized = true;
}

bool BgfxRenderer::Init(SDLWindow& window, int width, int height)
{
	m_width = width;
	m_height = height;

	bgfx::renderFrame();

	bgfx::Init init;
	init.type = bgfx::RendererType::Count;
	init.resolution.width = width;
	init.resolution.height = height;
	init.resolution.reset = BGFX_RESET_VSYNC;
	init.platformData.nwh = window.GetNativeWindowHandle();
	init.platformData.ndt = window.GetNativeDisplayHandle();

	if (!bgfx::init(init))
		return false;

	bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x1a1a2eff, 1.0f, 0);
	bgfx::setViewRect(0, 0, 0, (uint16_t)width, (uint16_t)height);

	for (int i = 0; i < STACK_DEPTH; i++)
	{
		bx::mtxIdentity(m_modelViewStack[i]);
		bx::mtxIdentity(m_projectionStack[i]);
	}
	bx::mtxIdentity(m_textureMatrix);

	m_mvTop = 0;
	m_projTop = 0;
	m_currentMode = 0;

	memset(m_texSlots, 0, sizeof(m_texSlots));
	for (int i = 0; i < MAX_TEXTURES; i++)
		m_texSlots[i].bgfxHandle = 0xFFFF;

	m_texColorUniform = bgfx::createUniform("s_texColor", bgfx::UniformType::Sampler).idx;

	// 1x1 white fallback texture for untextured draws
	{
		uint32_t white = 0xFFFFFFFF;
		const bgfx::Memory* mem = bgfx::copy(&white, 4);
		bgfx::TextureHandle th = bgfx::createTexture2D(1, 1, false, 1, bgfx::TextureFormat::RGBA8, 0, mem);
		m_whiteTexture = th.idx;
	}

	InitVertexLayouts();
	LoadShaders();

	return true;
}

void BgfxRenderer::LoadShaders()
{
	if (m_shadersLoaded) return;

	const uint8_t* vsData = nullptr;
	uint32_t vsSize = 0;
	const uint8_t* fsData = nullptr;
	uint32_t fsSize = 0;

	bgfx::RendererType::Enum type = bgfx::getRendererType();
	switch (type)
	{
	case bgfx::RendererType::Direct3D11:
	case bgfx::RendererType::Direct3D12:
		vsData = vs_minecraft_d3d11; vsSize = sizeof(vs_minecraft_d3d11);
		fsData = fs_minecraft_d3d11; fsSize = sizeof(fs_minecraft_d3d11);
		break;
	case bgfx::RendererType::OpenGL:
	case bgfx::RendererType::OpenGLES:
		vsData = vs_minecraft_glsl; vsSize = sizeof(vs_minecraft_glsl);
		fsData = fs_minecraft_glsl; fsSize = sizeof(fs_minecraft_glsl);
		break;
	case bgfx::RendererType::Metal:
#ifdef MINECRAFT_HAS_METAL_SHADERS
		vsData = vs_minecraft_mtl; vsSize = sizeof(vs_minecraft_mtl);
		fsData = fs_minecraft_mtl; fsSize = sizeof(fs_minecraft_mtl);
		break;
#endif
		[[fallthrough]];
	default:
		vsData = vs_minecraft_d3d11; vsSize = sizeof(vs_minecraft_d3d11);
		fsData = fs_minecraft_d3d11; fsSize = sizeof(fs_minecraft_d3d11);
		break;
	}

	bgfx::ShaderHandle vsh = bgfx::createShader(bgfx::copy(vsData, vsSize));
	bgfx::ShaderHandle fsh = bgfx::createShader(bgfx::copy(fsData, fsSize));
	m_program = bgfx::createProgram(vsh, fsh, true).idx;
	m_shadersLoaded = true;
}

void BgfxRenderer::Shutdown()
{
	bgfx::ProgramHandle prog = { m_program };
	if (bgfx::isValid(prog))
		bgfx::destroy(prog);
	m_program = 0xFFFF;

	bgfx::UniformHandle uh = { m_texColorUniform };
	if (bgfx::isValid(uh))
		bgfx::destroy(uh);

	for (int i = 0; i < MAX_TEXTURES; i++)
	{
		if (m_texSlots[i].used)
		{
			bgfx::TextureHandle th = { m_texSlots[i].bgfxHandle };
			if (bgfx::isValid(th))
				bgfx::destroy(th);
			m_texSlots[i].used = false;
		}
	}

	bgfx::shutdown();
}

void BgfxRenderer::Resize(int width, int height)
{
	m_width = width;
	m_height = height;
	bgfx::reset((uint32_t)width, (uint32_t)height, BGFX_RESET_VSYNC);
	bgfx::setViewRect(0, 0, 0, (uint16_t)width, (uint16_t)height);
}

void BgfxRenderer::Tick() {}
void BgfxRenderer::UpdateGamma(unsigned short) {}

void BgfxRenderer::StartFrame()
{
	bgfx::touch(0);
}

void BgfxRenderer::DoScreenGrabOnNextPresent() {}

void BgfxRenderer::Present()
{
	bgfx::frame();
}

void BgfxRenderer::Clear(int flags, void*)
{
	uint32_t rgba =
		((uint32_t)(m_clearColor[0] * 255) << 24) |
		((uint32_t)(m_clearColor[1] * 255) << 16) |
		((uint32_t)(m_clearColor[2] * 255) << 8) |
		((uint32_t)(m_clearColor[3] * 255));

	uint16_t clearFlags = 0;
	if (flags & 2) clearFlags |= BGFX_CLEAR_COLOR;
	if (flags & 1) clearFlags |= BGFX_CLEAR_DEPTH;

	bgfx::setViewClear(0, clearFlags, rgba, 1.0f, 0);
}

void BgfxRenderer::SetClearColour(const float rgba[4])
{
	memcpy(m_clearColor, rgba, sizeof(float) * 4);
}

bool BgfxRenderer::IsWidescreen() { return m_width > m_height; }
bool BgfxRenderer::IsHiDef() { return m_height >= 720; }

void BgfxRenderer::CaptureThumbnail(ImageFileBuffer*) {}
void BgfxRenderer::CaptureScreen(ImageFileBuffer*, XSOCIAL_PREVIEWIMAGE*) {}
void BgfxRenderer::BeginConditionalSurvey(int) {}
void BgfxRenderer::EndConditionalSurvey() {}
void BgfxRenderer::BeginConditionalRendering(int) {}
void BgfxRenderer::EndConditionalRendering() {}

void BgfxRenderer::Initialise(void*, void*) {}
void BgfxRenderer::InitialiseContext() {}

void BgfxRenderer::MatrixMode(int type) { m_currentMode = type; }

float* BgfxRenderer::GetCurrentMatrix()
{
	switch (m_currentMode)
	{
	case 0: return m_modelViewStack[m_mvTop];
	case 1: return m_projectionStack[m_projTop];
	case 2: return m_textureMatrix;
	default: return m_modelViewStack[m_mvTop];
	}
}

void BgfxRenderer::MatrixSetIdentity()
{
	bx::mtxIdentity(GetCurrentMatrix());
}

void BgfxRenderer::MatrixTranslate(float x, float y, float z)
{
	float tmp[16];
	bx::mtxTranslate(tmp, x, y, z);
	float* cur = GetCurrentMatrix();
	float result[16];
	bx::mtxMul(result, cur, tmp);
	memcpy(cur, result, sizeof(float) * 16);
}

void BgfxRenderer::MatrixRotate(float angle, float x, float y, float z)
{
	// angle is already in radians (glWrapper converts degrees→radians before calling)
	float rad = angle;
	float tmp[16];

	if (x == 0.0f && y == 0.0f && z != 0.0f)
		bx::mtxRotateZ(tmp, z > 0 ? rad : -rad);
	else if (x == 0.0f && y != 0.0f && z == 0.0f)
		bx::mtxRotateY(tmp, y > 0 ? rad : -rad);
	else if (x != 0.0f && y == 0.0f && z == 0.0f)
		bx::mtxRotateX(tmp, x > 0 ? rad : -rad);
	else
	{
		float len = bx::sqrt(x*x + y*y + z*z);
		if (len < 1e-6f) return;
		float nx = x/len, ny = y/len, nz = z/len;
		float c = bx::cos(rad), s = bx::sin(rad), t = 1.0f - c;
		tmp[ 0] = t*nx*nx + c;    tmp[ 1] = t*nx*ny + s*nz; tmp[ 2] = t*nx*nz - s*ny; tmp[ 3] = 0.0f;
		tmp[ 4] = t*nx*ny - s*nz; tmp[ 5] = t*ny*ny + c;    tmp[ 6] = t*ny*nz + s*nx; tmp[ 7] = 0.0f;
		tmp[ 8] = t*nx*nz + s*ny; tmp[ 9] = t*ny*nz - s*nx; tmp[10] = t*nz*nz + c;    tmp[11] = 0.0f;
		tmp[12] = 0.0f;           tmp[13] = 0.0f;            tmp[14] = 0.0f;            tmp[15] = 1.0f;
	}

	float* cur = GetCurrentMatrix();
	float result[16];
	bx::mtxMul(result, cur, tmp);
	memcpy(cur, result, sizeof(float) * 16);
}

void BgfxRenderer::MatrixScale(float x, float y, float z)
{
	float tmp[16];
	bx::mtxScale(tmp, x, y, z);
	float* cur = GetCurrentMatrix();
	float result[16];
	bx::mtxMul(result, cur, tmp);
	memcpy(cur, result, sizeof(float) * 16);
}

void BgfxRenderer::MatrixPerspective(float fovy, float aspect, float zNear, float zFar)
{
	float* cur = GetCurrentMatrix();
	bx::mtxProj(cur, fovy, aspect, zNear, zFar, bgfx::getCaps()->homogeneousDepth);
}

void BgfxRenderer::MatrixOrthogonal(float left, float right, float bottom, float top, float zNear, float zFar)
{
	float* cur = GetCurrentMatrix();
	bx::mtxOrtho(cur, left, right, bottom, top, zNear, zFar, 0.0f, bgfx::getCaps()->homogeneousDepth);
}

void BgfxRenderer::MatrixPush()
{
	if (m_currentMode == 0 && m_mvTop < STACK_DEPTH - 1)
	{
		memcpy(m_modelViewStack[m_mvTop + 1], m_modelViewStack[m_mvTop], sizeof(float) * 16);
		m_mvTop++;
	}
	else if (m_currentMode == 1 && m_projTop < STACK_DEPTH - 1)
	{
		memcpy(m_projectionStack[m_projTop + 1], m_projectionStack[m_projTop], sizeof(float) * 16);
		m_projTop++;
	}
}

void BgfxRenderer::MatrixPop()
{
	if (m_currentMode == 0 && m_mvTop > 0)
		m_mvTop--;
	else if (m_currentMode == 1 && m_projTop > 0)
		m_projTop--;
}

void BgfxRenderer::MatrixMult(float* mat)
{
	float* cur = GetCurrentMatrix();
	float result[16];
	bx::mtxMul(result, cur, mat);
	memcpy(cur, result, sizeof(float) * 16);
}

const float* BgfxRenderer::MatrixGet(int type)
{
	switch (type)
	{
	case 0: return m_modelViewStack[m_mvTop];
	case 1: return m_projectionStack[m_projTop];
	case 2: return m_textureMatrix;
	default: return m_modelViewStack[m_mvTop];
	}
}

void BgfxRenderer::Set_matrixDirty() {}

// GL blend factor enum → bgfx blend constant
static uint64_t GLBlendToBgfx(int glFactor)
{
	switch (glFactor)
	{
	case 1:  return BGFX_STATE_BLEND_ZERO;           // GL_ZERO
	case 2:  return BGFX_STATE_BLEND_ONE;            // GL_ONE
	case 3:  return BGFX_STATE_BLEND_SRC_COLOR;      // GL_SRC_COLOR
	case 4:  return BGFX_STATE_BLEND_INV_SRC_COLOR;  // GL_ONE_MINUS_SRC_COLOR
	case 5:  return BGFX_STATE_BLEND_SRC_ALPHA;      // GL_SRC_ALPHA
	case 6:  return BGFX_STATE_BLEND_INV_SRC_ALPHA;  // GL_ONE_MINUS_SRC_ALPHA
	case 7:  return BGFX_STATE_BLEND_DST_ALPHA;      // GL_DST_ALPHA
	case 9:  return BGFX_STATE_BLEND_DST_COLOR;      // GL_DST_COLOR
	case 10: return BGFX_STATE_BLEND_INV_DST_COLOR;  // GL_ONE_MINUS_DST_COLOR
	default: return BGFX_STATE_BLEND_ONE;
	}
}

uint64_t BgfxRenderer::BuildBgfxState() const
{
	uint64_t state = BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A;

	if (m_depthTestEnabled)
	{
		switch (m_depthFunc)
		{
		case 4:  state |= BGFX_STATE_DEPTH_TEST_LEQUAL; break;  // GL_LEQUAL
		case 5:  state |= BGFX_STATE_DEPTH_TEST_GREATER; break; // GL_GREATER
		case 3:  state |= BGFX_STATE_DEPTH_TEST_EQUAL; break;   // GL_EQUAL
		case 7:  state |= BGFX_STATE_DEPTH_TEST_GEQUAL; break;  // GL_GEQUAL
		case 8:  state |= BGFX_STATE_DEPTH_TEST_ALWAYS; break;  // GL_ALWAYS
		default: state |= BGFX_STATE_DEPTH_TEST_LESS; break;
		}
	}

	if (m_depthWriteEnabled)
		state |= BGFX_STATE_WRITE_Z;

	if (m_blendEnabled)
		state |= BGFX_STATE_BLEND_FUNC(GLBlendToBgfx(m_blendSrc), GLBlendToBgfx(m_blendDst));

	if (m_cullEnabled)
		state |= m_cullCW ? BGFX_STATE_CULL_CW : BGFX_STATE_CULL_CCW;

	if (m_alphaTestEnabled && m_alphaRef > 0.0f)
		state |= BGFX_STATE_BLEND_ALPHA_TO_COVERAGE;

	return state;
}

void BgfxRenderer::ConvertQuadsToTriangles(const void* quadData, int quadVertCount, int vertexStride, void* triOut, int& triVertCount) const
{
	// every 4 vertices (quad) → 6 vertices (2 triangles): (v0,v1,v2), (v0,v2,v3)
	int numQuads = quadVertCount / 4;
	triVertCount = numQuads * 6;
	const uint8_t* src = (const uint8_t*)quadData;
	uint8_t* dst = (uint8_t*)triOut;

	for (int q = 0; q < numQuads; q++)
	{
		const uint8_t* v0 = src + (q * 4 + 0) * vertexStride;
		const uint8_t* v1 = src + (q * 4 + 1) * vertexStride;
		const uint8_t* v2 = src + (q * 4 + 2) * vertexStride;
		const uint8_t* v3 = src + (q * 4 + 3) * vertexStride;

		memcpy(dst, v0, vertexStride); dst += vertexStride;
		memcpy(dst, v1, vertexStride); dst += vertexStride;
		memcpy(dst, v2, vertexStride); dst += vertexStride;
		memcpy(dst, v0, vertexStride); dst += vertexStride;
		memcpy(dst, v2, vertexStride); dst += vertexStride;
		memcpy(dst, v3, vertexStride); dst += vertexStride;
	}
}

void BgfxRenderer::SubmitDraw(ePrimitiveType primType, int count, void* dataIn, eVertexType vType,
							  int texIdx, float mvMatrix[16], float projMatrix[16])
{
	if (!m_shadersLoaded || count <= 0 || !dataIn)
		return;

	if (vType == VERTEX_TYPE_COMPRESSED)
		return;

	const int vertexStride = 32;
	int drawVertCount = count;
	uint8_t* vertexData = nullptr;

	if (primType == PRIMITIVE_TYPE_QUAD_LIST)
	{
		int triVertCount = 0;
		int numQuads = count / 4;
		vertexData = new uint8_t[numQuads * 6 * vertexStride];
		ConvertQuadsToTriangles(dataIn, count, vertexStride, vertexData, triVertCount);
		drawVertCount = triVertCount;
		primType = PRIMITIVE_TYPE_TRIANGLE_LIST;
	}
	else if (primType == PRIMITIVE_TYPE_TRIANGLE_FAN && count >= 3)
	{
		// fan (v0,v1,...,vN) → triangles (v0,v1,v2), (v0,v2,v3), ..., (v0,vN-1,vN)
		int numTris = count - 2;
		drawVertCount = numTris * 3;
		vertexData = new uint8_t[drawVertCount * vertexStride];
		const uint8_t* src = (const uint8_t*)dataIn;
		uint8_t* dst = vertexData;
		for (int t = 0; t < numTris; t++)
		{
			memcpy(dst, src, vertexStride); dst += vertexStride; // v0
			memcpy(dst, src + (t + 1) * vertexStride, vertexStride); dst += vertexStride;
			memcpy(dst, src + (t + 2) * vertexStride, vertexStride); dst += vertexStride;
		}
		primType = PRIMITIVE_TYPE_TRIANGLE_LIST;
	}
	else
	{
		vertexData = new uint8_t[count * vertexStride];
		memcpy(vertexData, dataIn, count * vertexStride);
		drawVertCount = count;
	}

	// color at offset 20: game stores (R<<24|G<<16|B<<8|A), need [R,G,B,A] bytes for bgfx
	for (int i = 0; i < drawVertCount; i++)
	{
		uint8_t* c = vertexData + i * vertexStride + 20;
		uint8_t a = c[0], b = c[1], g = c[2], r = c[3];
		c[0] = r; c[1] = g; c[2] = b; c[3] = a;
	}

	bgfx::TransientVertexBuffer tvb;
	if (!bgfx::getAvailTransientVertexBuffer(drawVertCount, s_standardLayout))
	{
		delete[] vertexData;
		return;
	}
	bgfx::allocTransientVertexBuffer(&tvb, drawVertCount, s_standardLayout);
	memcpy(tvb.data, vertexData, drawVertCount * vertexStride);
	delete[] vertexData;

	bgfx::setVertexBuffer(0, &tvb);

	// white fallback if no texture bound
	{
		bgfx::UniformHandle uh = { m_texColorUniform };
		bgfx::TextureHandle th = { m_whiteTexture };
		if (texIdx >= 0 && texIdx < MAX_TEXTURES && m_texSlots[texIdx].used)
		{
			bgfx::TextureHandle texHandle = { m_texSlots[texIdx].bgfxHandle };
			if (bgfx::isValid(texHandle))
				th = texHandle;
		}
		if (bgfx::isValid(th) && bgfx::isValid(uh))
			bgfx::setTexture(0, uh, th);
	}

	float mvp[16];
	bx::mtxMul(mvp, mvMatrix, projMatrix);
	bgfx::setTransform(mvp);

	uint64_t state = BuildBgfxState();
	switch (primType)
	{
	case PRIMITIVE_TYPE_TRIANGLE_STRIP: state |= BGFX_STATE_PT_TRISTRIP; break;
	case PRIMITIVE_TYPE_LINE_LIST:      state |= BGFX_STATE_PT_LINES;    break;
	case PRIMITIVE_TYPE_LINE_STRIP:     state |= BGFX_STATE_PT_LINESTRIP; break;
	default: break;
	}
	bgfx::setState(state);

	bgfx::ProgramHandle prog = { m_program };
	bgfx::submit(0, prog);
}

void BgfxRenderer::DrawVertices(ePrimitiveType primType, int count, void* dataIn, eVertexType vType, ePixelShaderType psType)
{
	if (count <= 0 || !dataIn)
		return;

	if (vType == VERTEX_TYPE_COMPRESSED)
		return;

	const int vertexStride = 32;

	if (m_recordingBuffer >= 0 && m_cmdBuffers)
	{
		CmdBuffer& cb = m_cmdBuffers[m_recordingBuffer];
		RecordedDraw draw;
		draw.primType = primType;
		draw.vType = vType;
		draw.vertCount = count;
		draw.texIdx = m_boundTexture;
		memcpy(draw.mvMatrix, m_modelViewStack[m_mvTop], 64);
		memcpy(draw.projMatrix, m_projectionStack[m_projTop], 64);
		draw.blendEnabled = m_blendEnabled;
		draw.blendSrc = m_blendSrc;
		draw.blendDst = m_blendDst;
		draw.depthTestEnabled = m_depthTestEnabled;
		draw.depthWriteEnabled = m_depthWriteEnabled;
		draw.depthFunc = m_depthFunc;
		draw.cullEnabled = m_cullEnabled;
		draw.cullCW = m_cullCW;
		draw.alphaTestEnabled = m_alphaTestEnabled;
		draw.alphaRef = m_alphaRef;
		int dataSize = count * vertexStride;
		draw.vertexData = new uint8_t[dataSize];
		memcpy(draw.vertexData, dataIn, dataSize);
		cb.AddDraw(draw);
		return;
	}

	SubmitDraw(primType, count, dataIn, vType, m_boundTexture,
			   m_modelViewStack[m_mvTop], m_projectionStack[m_projTop]);
}

void BgfxRenderer::DrawVertexBuffer(ePrimitiveType primType, int count, void* buffer, eVertexType vType, ePixelShaderType psType)
{
	DrawVertices(primType, count, buffer, vType, psType);
}

void BgfxRenderer::CmdBuffer::Clear()
{
	for (int i = 0; i < drawCount; i++)
		delete[] draws[i].vertexData;
	drawCount = 0;
	totalBytes = 0;
}

void BgfxRenderer::CmdBuffer::AddDraw(const RecordedDraw& draw)
{
	if (drawCount >= drawCapacity)
	{
		int newCap = drawCapacity == 0 ? 64 : drawCapacity * 2;
		RecordedDraw* newDraws = new RecordedDraw[newCap];
		if (draws)
		{
			memcpy(newDraws, draws, drawCount * sizeof(RecordedDraw));
			delete[] draws;
		}
		draws = newDraws;
		drawCapacity = newCap;
	}
	draws[drawCount++] = draw;
	totalBytes += draw.vertCount * 32 + sizeof(RecordedDraw);
}

BgfxRenderer::CmdBuffer::~CmdBuffer()
{
	Clear();
	delete[] draws;
}

void BgfxRenderer::EnsureCmdBuffers()
{
	if (!m_cmdBuffers)
	{
		m_cmdBuffers = new CmdBuffer[MAX_CMD_BUFFERS];
	}
}

void BgfxRenderer::CBuffLockStaticCreations() {}

int BgfxRenderer::CBuffCreate(int count)
{
	EnsureCmdBuffers();
	int first = m_nextCmdBufferId;

	for (int start = 1; start < MAX_CMD_BUFFERS - count; start++)
	{
		bool ok = true;
		for (int i = 0; i < count; i++)
		{
			if (m_cmdBuffers[start + i].allocated)
			{
				ok = false;
				break;
			}
		}
		if (ok)
		{
			for (int i = 0; i < count; i++)
				m_cmdBuffers[start + i].allocated = true;
			if (start + count > m_nextCmdBufferId)
				m_nextCmdBufferId = start + count;
			return start;
		}
	}
	return 0;
}

void BgfxRenderer::CBuffDelete(int first, int count)
{
	if (!m_cmdBuffers) return;
	for (int i = 0; i < count; i++)
	{
		int idx = first + i;
		if (idx > 0 && idx < MAX_CMD_BUFFERS)
		{
			m_cmdBuffers[idx].Clear();
			m_cmdBuffers[idx].allocated = false;
		}
	}
}

void BgfxRenderer::CBuffStart(int index, bool)
{
	EnsureCmdBuffers();
	if (index > 0 && index < MAX_CMD_BUFFERS)
	{
		m_cmdBuffers[index].Clear();
		m_cmdBuffers[index].allocated = true;
		m_recordingBuffer = index;
	}
}

void BgfxRenderer::CBuffClear(int index)
{
	if (!m_cmdBuffers) return;
	if (index > 0 && index < MAX_CMD_BUFFERS)
		m_cmdBuffers[index].Clear();
}

int BgfxRenderer::CBuffSize(int index)
{
	if (!m_cmdBuffers) return 0;
	if (index == -1)
	{
		int total = 0;
		for (int i = 0; i < MAX_CMD_BUFFERS; i++)
			if (m_cmdBuffers[i].allocated)
				total += m_cmdBuffers[i].totalBytes;
		return total;
	}
	if (index > 0 && index < MAX_CMD_BUFFERS)
		return m_cmdBuffers[index].totalBytes;
	return 0;
}

void BgfxRenderer::CBuffEnd()
{
	m_recordingBuffer = -1;
}

bool BgfxRenderer::CBuffCall(int index, bool)
{
	if (!m_cmdBuffers || !m_shadersLoaded) return false;
	if (index <= 0 || index >= MAX_CMD_BUFFERS) return false;

	CmdBuffer& cb = m_cmdBuffers[index];
	if (!cb.allocated || cb.drawCount == 0) return false;

	bool savedBlend = m_blendEnabled;
	int savedBlendSrc = m_blendSrc, savedBlendDst = m_blendDst;
	bool savedDepthTest = m_depthTestEnabled;
	bool savedDepthWrite = m_depthWriteEnabled;
	int savedDepthFunc = m_depthFunc;
	bool savedCull = m_cullEnabled;
	bool savedCullCW = m_cullCW;
	bool savedAlphaTest = m_alphaTestEnabled;
	float savedAlphaRef = m_alphaRef;

	for (int i = 0; i < cb.drawCount; i++)
	{
		RecordedDraw& draw = cb.draws[i];

		m_blendEnabled = draw.blendEnabled;
		m_blendSrc = draw.blendSrc;
		m_blendDst = draw.blendDst;
		m_depthTestEnabled = draw.depthTestEnabled;
		m_depthWriteEnabled = draw.depthWriteEnabled;
		m_depthFunc = draw.depthFunc;
		m_cullEnabled = draw.cullEnabled;
		m_cullCW = draw.cullCW;
		m_alphaTestEnabled = draw.alphaTestEnabled;
		m_alphaRef = draw.alphaRef;

		SubmitDraw(draw.primType, draw.vertCount, draw.vertexData, draw.vType,
				   draw.texIdx, draw.mvMatrix, draw.projMatrix);
	}

	m_blendEnabled = savedBlend;
	m_blendSrc = savedBlendSrc; m_blendDst = savedBlendDst;
	m_depthTestEnabled = savedDepthTest;
	m_depthWriteEnabled = savedDepthWrite;
	m_depthFunc = savedDepthFunc;
	m_cullEnabled = savedCull;
	m_cullCW = savedCullCW;
	m_alphaTestEnabled = savedAlphaTest;
	m_alphaRef = savedAlphaRef;

	return true;
}

void BgfxRenderer::CBuffTick() {}
void BgfxRenderer::CBuffDeferredModeStart() { m_deferredMode = true; }
void BgfxRenderer::CBuffDeferredModeEnd() { m_deferredMode = false; }

int BgfxRenderer::AllocTextureSlot()
{
	for (int i = 0; i < MAX_TEXTURES; i++)
		if (!m_texSlots[i].used)
		{
			m_texSlots[i].used = true;
			return i;
		}
	return -1;
}

void BgfxRenderer::FreeTextureSlot(int idx)
{
	if (idx >= 0 && idx < MAX_TEXTURES)
	{
		bgfx::TextureHandle th = { m_texSlots[idx].bgfxHandle };
		if (bgfx::isValid(th))
			bgfx::destroy(th);
		m_texSlots[idx] = {};
		m_texSlots[idx].bgfxHandle = 0xFFFF;
	}
}

int BgfxRenderer::TextureCreate()
{
	return AllocTextureSlot();
}

void BgfxRenderer::TextureFree(int idx)
{
	FreeTextureSlot(idx);
}

void BgfxRenderer::TextureBind(int idx)
{
	// actual setTexture happens in SubmitDraw
	m_boundTexture = idx;
}

void BgfxRenderer::TextureBindVertex(int idx)
{
	// actual setTexture happens in SubmitDraw
	m_boundTexture = idx;
}

void BgfxRenderer::TextureSetTextureLevels(int levels)
{
	m_textureLevels = levels;
}

int BgfxRenderer::TextureGetTextureLevels()
{
	return m_textureLevels;
}

// converts ARGB int array → RGBA byte order for bgfx
static const bgfx::Memory* ConvertARGBtoRGBA(const void* data, int width, int height)
{
	if (!data) return nullptr;
	int pixelCount = width * height;
	const bgfx::Memory* mem = bgfx::alloc(pixelCount * 4);
	const uint32_t* src = (const uint32_t*)data;
	uint8_t* dst = mem->data;
	for (int i = 0; i < pixelCount; i++)
	{
		uint32_t argb = src[i];
		dst[i * 4 + 0] = (uint8_t)(argb >> 16); // R
		dst[i * 4 + 1] = (uint8_t)(argb >> 8);  // G
		dst[i * 4 + 2] = (uint8_t)(argb);       // B
		dst[i * 4 + 3] = (uint8_t)(argb >> 24); // A
	}
	return mem;
}

void BgfxRenderer::TextureData(int width, int height, void* data, int level, eTextureFormat)
{
	if (m_boundTexture < 0 || m_boundTexture >= MAX_TEXTURES)
		return;
	TextureSlot& slot = m_texSlots[m_boundTexture];

	if (level == 0)
	{
		bgfx::TextureHandle old = { slot.bgfxHandle };
		if (bgfx::isValid(old))
			bgfx::destroy(old);

		slot.width = width;
		slot.height = height;

		// create without initial data so mip levels can be uploaded via updateTexture2D
		bgfx::TextureHandle th = bgfx::createTexture2D(
			(uint16_t)width, (uint16_t)height,
			m_textureLevels > 1, 1,
			bgfx::TextureFormat::RGBA8,
			BGFX_SAMPLER_U_CLAMP | BGFX_SAMPLER_V_CLAMP,
			nullptr);
		slot.bgfxHandle = th.idx;
	}

	if (data)
	{
		bgfx::TextureHandle th = { slot.bgfxHandle };
		if (bgfx::isValid(th))
		{
			const bgfx::Memory* mem = ConvertARGBtoRGBA(data, width, height);
			bgfx::updateTexture2D(th, 0, (uint8_t)level, 0, 0, (uint16_t)width, (uint16_t)height, mem);
		}
	}
}

void BgfxRenderer::TextureDataUpdate(int xoffset, int yoffset, int width, int height, void* data, int level)
{
	if (m_boundTexture < 0 || m_boundTexture >= MAX_TEXTURES || !data)
		return;
	TextureSlot& slot = m_texSlots[m_boundTexture];
	bgfx::TextureHandle th = { slot.bgfxHandle };
	if (bgfx::isValid(th))
	{
		const bgfx::Memory* mem = ConvertARGBtoRGBA(data, width, height);
		bgfx::updateTexture2D(th, 0, (uint8_t)level,
			(uint16_t)xoffset, (uint16_t)yoffset,
			(uint16_t)width, (uint16_t)height, mem);
	}
}

void BgfxRenderer::TextureSetParam(int, int) {}
void BgfxRenderer::TextureDynamicUpdateStart() {}
void BgfxRenderer::TextureDynamicUpdateEnd() {}

long BgfxRenderer::LoadTextureData(const char* szFilename, D3DXIMAGE_INFO* pSrcInfo, int** ppDataOut)
{
	if (!szFilename || !pSrcInfo || !ppDataOut)
		return -1;

	FILE* f = fopen(szFilename, "rb");
	if (!f)
		return -1;

	fseek(f, 0, SEEK_END);
	long fileSize = ftell(f);
	fseek(f, 0, SEEK_SET);

	unsigned char* fileData = new unsigned char[fileSize];
	fread(fileData, 1, fileSize, f);
	fclose(f);

	long result = LoadTextureData(fileData, (unsigned long)fileSize, pSrcInfo, ppDataOut);
	delete[] fileData;
	return result;
}

long BgfxRenderer::LoadTextureData(unsigned char* pbData, unsigned long dwBytes, D3DXIMAGE_INFO* pSrcInfo, int** ppDataOut)
{
	if (!pbData || dwBytes == 0 || !pSrcInfo || !ppDataOut)
		return -1;

	int w = 0, h = 0, channels = 0;
	unsigned char* pixels = stbi_load_from_memory(pbData, (int)dwBytes, &w, &h, &channels, 4);
	if (!pixels)
		return -1;

	pSrcInfo->Width = w;
	pSrcInfo->Height = h;

	// stb returns RGBA bytes; game expects ARGB as int (A<<24|R<<16|G<<8|B)
	int* outData = new int[w * h];
	for (int i = 0; i < w * h; i++)
	{
		unsigned char r = pixels[i * 4 + 0];
		unsigned char g = pixels[i * 4 + 1];
		unsigned char b = pixels[i * 4 + 2];
		unsigned char a = pixels[i * 4 + 3];
		outData[i] = (a << 24) | (r << 16) | (g << 8) | b;
	}

	stbi_image_free(pixels);
	*ppDataOut = outData;
	return 0; // ERROR_SUCCESS
}
long BgfxRenderer::SaveTextureData(const char*, D3DXIMAGE_INFO*, int*) { return -1; }
long BgfxRenderer::SaveTextureDataToMemory(void*, int, int*, int, int, int*) { return -1; }
void BgfxRenderer::TextureGetStats() {}
void* BgfxRenderer::TextureGetTexture(int) { return nullptr; }

void BgfxRenderer::StateSetColour(float r, float g, float b, float a)
{
	m_colour[0] = r; m_colour[1] = g; m_colour[2] = b; m_colour[3] = a;
}

void BgfxRenderer::StateSetDepthMask(bool enable) { m_depthWriteEnabled = enable; }
void BgfxRenderer::StateSetBlendEnable(bool enable) { m_blendEnabled = enable; }
void BgfxRenderer::StateSetBlendFunc(int src, int dst) { m_blendSrc = src; m_blendDst = dst; }
void BgfxRenderer::StateSetBlendFactor(unsigned int) {}
void BgfxRenderer::StateSetAlphaFunc(int, float ref) { m_alphaRef = ref; }
void BgfxRenderer::StateSetDepthFunc(int func) { m_depthFunc = func; }
void BgfxRenderer::StateSetFaceCull(bool enable) { m_cullEnabled = enable; }
void BgfxRenderer::StateSetFaceCullCW(bool enable) { m_cullCW = enable; }
void BgfxRenderer::StateSetLineWidth(float) {}
void BgfxRenderer::StateSetWriteEnable(bool, bool, bool, bool) {}
void BgfxRenderer::StateSetDepthTestEnable(bool enable) { m_depthTestEnabled = enable; }
void BgfxRenderer::StateSetAlphaTestEnable(bool enable) { m_alphaTestEnabled = enable; }
void BgfxRenderer::StateSetDepthSlopeAndBias(float, float) {}
void BgfxRenderer::StateSetFogEnable(bool enable) { m_fogEnabled = enable; }
void BgfxRenderer::StateSetFogMode(int) {}
void BgfxRenderer::StateSetFogNearDistance(float dist) { m_fogNear = dist; }
void BgfxRenderer::StateSetFogFarDistance(float dist) { m_fogFar = dist; }
void BgfxRenderer::StateSetFogDensity(float) {}
void BgfxRenderer::StateSetFogColour(float r, float g, float b)
{
	m_fogColor[0] = r; m_fogColor[1] = g; m_fogColor[2] = b;
}
void BgfxRenderer::StateSetLightingEnable(bool enable) { m_lightingEnabled = enable; }
void BgfxRenderer::StateSetVertexTextureUV(float, float) {}
void BgfxRenderer::StateSetLightColour(int, float, float, float) {}
void BgfxRenderer::StateSetLightAmbientColour(float, float, float) {}
void BgfxRenderer::StateSetLightDirection(int, float, float, float) {}
void BgfxRenderer::StateSetLightEnable(int, bool) {}
void BgfxRenderer::StateSetViewport(eViewportType) {}
void BgfxRenderer::StateSetEnableViewportClipPlanes(bool) {}
void BgfxRenderer::StateSetTexGenCol(int, float, float, float, float, bool) {}
void BgfxRenderer::StateSetStencil(int, uint8_t, uint8_t, uint8_t) {}
void BgfxRenderer::StateSetForceLOD(int) {}

void BgfxRenderer::BeginEvent(const wchar_t*) {}
void BgfxRenderer::EndEvent() {}

void BgfxRenderer::Suspend() { m_suspended = true; }
bool BgfxRenderer::Suspended() { return m_suspended; }
void BgfxRenderer::Resume() { m_suspended = false; }
